#:kivy 2.2.0

MainScreen:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

HistoryScreen:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

GeneratorScreen:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

SettingsScreen:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

Label:
    color: 1, 1, 1, 1

Button:
    background_color: 0.3, 0.3, 0.3, 1
    color: 1, 1, 1, 1

TextInput:
    background_color: 0.4, 0.4, 0.4, 1
    foreground_color: 1, 1, 1, 1
